version: '3.1'
services:
  sunmait-career-day-dev:
    image: sunmait-career-day-dev
    ports:
      - 3000:3000
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ../server/:/sunmait-career-day/server/
      - /sunmait-career-day/server/node_modules
      - /sunmait-career-day/server/API/node_modules
      - /sunmait-career-day/server/Data/node_modules
      - /sunmait-career-day/server/Domain/node_modules
    network_mode: host
    depends_on:
      - sunmait-career-day-devdb

  sunmait-career-day-devdb:
    image: postgres:11.1
    environment:
      POSTGRES_DB: sunmait_career_days_development
      POSTGRES_PASSWORD: my_password
    ports:
      - 5432:5432
    container_name: sunmait-career-day-devdb
    network_mode: host

  sunmait-career-day-seed:
    image: sunmait-career-day-dev:latest
    command: ./wait-for-db.sh sunmait-career-day-devdb:5432 -- npm run migrate-and-seed
    network_mode: host
    depends_on:
      - sunmait-career-day-devdb

  sunmait-career-day-client-dev-server:
    image: sunmait-career-day-dev:latest
    ports:
      - 3011:3011
    command: bash -c "cd ../client && npm run start"
    volumes:
      - ../client/:/sunmait-career-day/client/
      - /sunmait-career-day/client/node_modules
    network_mode: host
    depends_on:
      - sunmait-career-day-dev